{% set name = "stopt" %}
{% set version = "7.1" %}
{% set build = 0 %}
{% set mpi_label = mpi|replace("-devel", "") %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://gitlab.com/stochastic-control/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 8a9f585a4f043930b97eba8e2b9715b5ac83c5f14d90550314787bfecc44675a

build:
  number: {{ build }}
  string: mpi_{{ mpi_label }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage('stopt', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.15
    - make  # [unix]
    - pkgconfig  # [unix]
    - ninja  # [win]
    - impi-devel  # [win and mpi == "impi-devel"]
  host:
    - libboost-devel
    - libboost-mpi
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - llvm-openmp  # [win and mpi != "msmpi"]
    - intel-openmp  # [win and mpi == "msmpi"]
    - {{ mpi }}  # [not win]
    - impi-devel  # [win and mpi == "impi-devel"]
    - msmpi  # [win and mpi == "msmpi"]
    - eigen
    - coin-or-utils
    - coin-or-clp
    - coin-or-osi
    - bzip2
    - zlib
  run:
    - msmpi  # [win and mpi == "msmpi"]
    - pthreads-win32  # [win and mpi == "msmpi"]
  run_constrained:
    - msmpi <0a0  # [win and mpi != "msmpi"]
    - impi_rt <0a0  # [win and mpi == "msmpi"]

test:
  commands:
    - test -f $PREFIX/lib/libStOpt.so  # [linux]
    - test -f $PREFIX/lib/libgeners.so  # [linux]
    - test -f $PREFIX/lib/libStOpt.dylib  # [osx]
    - test -f $PREFIX/lib/libgeners.dylib  # [osx]
    - if not exist "%PREFIX%\\Library\\lib\\StOpt.lib" exit 1  # [win]
    - if not exist "%PREFIX%\\Library\\lib\\geners.lib" exit 1  # [win]
    - strings %LIBRARY_LIB%\\StOpt.lib | findstr /C:"RuntimeLibrary=MD"  # [win]
  requires:
    - binutils  # [win]

about:
  home: https://gitlab.com/stochastic-control/StOpt
  summary: 'Library for stochastic control'
  description: |
    The STochastic OPTimization library (StOpt) aims at providing tools in C++ for solvingsome stochastic optimization problems encountered in finance or in the industry.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://gitlab.com/stochastic-control/StOpt
  dev_url: https://gitlab.com/stochastic-control/StOpt

extra:
  recipe-maintainers:
    - davide-f
    - XWarin
